#! /usr/bin/env zsh
#
# Script para cuando aparece el siguiente error :
# zsh: corrupt history file /home/ivanse/.zsh_history
#
mv ~/.zsh_history ~/.zsh_history_con_error
strings -eS ~/.zsh_history_con_error > ~/.zsh_history
fc -R ~/.zsh_history
rm ~/.zsh_history_con_error

